# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pwdcalc"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kjel Delaey"]
  s.date = "2011-12-17"
  s.description = "Pwdcalc is a Rails 3 gem to create password field/-strength meter combinations. Take no risk and help your users to choose good passwords!"
  s.email = "kjel_delaey@hotmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "app/assets/javascripts/jquery.YAPSM.min.js",
    "app/assets/javascripts/jquery.pwdcalc.js",
    "lib/generators/pwdcalc/install/install_generator.rb",
    "lib/generators/pwdcalc/install/templates/pwdcalc.en.yml",
    "lib/pwdcalc.rb",
    "lib/pwdcalc/formtastic.rb",
    "lib/pwdcalc/helpers/hints.rb",
    "lib/pwdcalc/version.rb"
  ]
  s.homepage = "https://github.com/trimentor/pwdcalc"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.12"
  s.summary = "Calculates the strength of user-chosen passwords."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

